# RECOMMENDATION - DO NOT DELETE THIS FILE, RENAME IT AT BEST IF YOU KNOW 
# YOUR USER CONFIG IS COMPLETE.

# WARNING - REMOVING LINES FROM THIS FILE MAY HAVE UNEXPECTED RESULTS
# CUSTOMIZE VALUES SEEN BELOW USING A USER CONFIGURATION FILE (SEE EXAMPLE.TOML)

[general]
# Number of seconds to go back and retrieve data for when timestamps are involved
# Default: 60 seconds
backtrack = 60

[logging]
debug = false # Enables module-level verbosity, meant for development purposes

[kismet]
# @todo replace host/port with uri for https/http support, but urllib.parse, other https requirements
host = "127.0.0.1"
port = 2501
apikey = ""

[gravwell]
host = "127.0.0.1"
port = 80
token = ""

[gravwell.tags]
kismet_device = "kismet-device" # Tag to use for a device entity
kismet_status = "kismet-status" # Tag to use for a system status entity

[gravwell.tags.kismet.phy]
phydot11_accesspoints = "kismet-ap"
phy-IEEE802.11 = "kismet-wifi"
phy-RFSENSOR = "kismet-sensor"
phy-Z-Wave = "kismet-zwave"
phy-Bluetooth = "kismet-bt"
phy-UAV = "kismet-uav"
phy-NrfMousejack = "kismet-mousejack"
phy-BTLE = "kismet-btle"
phy-METER = "kismet-meter"
phy-ADSB = "kismet-adsb"
phy-802.15.4 = "kismet-lrwpan"
phy-RADIATION = "kismet-radiation"

# Advanced section

[kismet.ingest]
# @todo not implemented
system_status     = true # Ref: https://www.kismetwireless.net/docs/api/system/#system-status
# packet_stats    = false # Ref: https://www.kismetwireless.net/docs/api/system/#packet-statistics
# eventbus          = false # Ref: https://www.kismetwireless.net/docs/api/eventbus/#eventbus-websocket
# eventbus_topics   = ["ALERT", "BATTERY"] # Ref: https://www.kismetwireless.net/docs/api/eventbus/#eventbus-topics
devices           = true # Ref: https://www.kismetwireless.net/docs/api/device_views/#realtime-device-monitoring-by-view
devices_all       = false # Ref: https://www.kismetwireless.net/docs/api/device_views/#list-device-views
devices_phy       = ["phydot11_accesspoints", "phy-IEEE802.11"] # Ref: https://www.kismetwireless.net/docs/api/device_views/#list-device-views
# messages        = false # Ref: https://www.kismetwireless.net/docs/api/messages/#recent-messages
# alerts          = false # Ref: https://www.kismetwireless.net/docs/api/alerts/#recent-alerts
channels_summary  = true # Ref: https://www.kismetwireless.net/docs/api/channels/#channel-summary
# datasources     = false # Ref: https://www.kismetwireless.net/docs/api/datasources/#datasource-list

[kismet.intervals]
# WARNING: Short interval may not give Kismet enough time to respond to a query 
# before another comes in, leading to Kismet hangups, or worse.
system_status     = 10
# packet_stats    = 10
devices           = 60
# messages        = 10
# alerts          = 10
channels_summary  = 30
# datasources     = 10

[kismet.fields.devices]
# Common fields excludes RRD
common = [
  "kismet.device.base.key",
  "kismet.device.base.macaddr",
  "kismet.device.base.related_devices",
  "kismet.device.base.name",
  "kismet.device.base.commonname",
  "kismet.server.uuid",
  "kismet.device.base.basic_type_set",
  "kismet.device.base.crypt",
  "kismet.device.base.first_time",
  "kismet.device.base.last_time",
  "kismet.device.base.packets.total",
  "kismet.device.base.packets.rx_total",
  "kismet.device.base.packets.tx_total",
  "kismet.device.base.packets.llc",
  "kismet.device.base.packets.error",
  "kismet.device.base.packets.data",
  "kismet.device.base.packets.crypt",
  "kismet.device.base.packets.filtered",
  "kismet.device.base.datasize",
  "kismet.device.base.channel",
  "kismet.device.base.frequency",
  "kismet.device.base.freq_khz_map",
  "kismet.device.base.num_alerts",
  "kismet.device.base.seenby",
  "kismet.device.base.phyname",
  "kismet.device.base.manuf",
  "kismet.device.base.signal/kismet.common.signal.type",
  "kismet.device.base.signal/kismet.common.signal.last_signal",
  "kismet.device.base.signal/kismet.common.signal.last_noise",
  "kismet.device.base.signal/kismet.common.signal.min_signal",
  "kismet.device.base.signal/kismet.common.signal.min_noise",
  "kismet.device.base.signal/kismet.common.signal.max_signal",
  "kismet.device.base.signal/kismet.common.signal.max_noise",
  "kismet.device.base.signal/kismet.common.signal.maxseenrate",
  "kismet.device.base.signal/kismet.common.signal.encodingset",
  "kismet.device.base.signal/kismet.common.signal.carrierset",
  "kismet.device.base.location",
  "kismet.device.base.type",
  "dot11.device",
  "sensor.device",
  "zwave.device",
  "bluetooth.device",
  "uav.device",
  "nrfmousejack.device",
  "btle.device",
  "meter.device",
  "adsb.device",
  "802154.device",
]
all = []
phydot11_accesspoints = []
phy-IEEE802.11 = []
phy-RFSENSOR = []
phy-Z-Wave = []
phy-Bluetooth = []
phy-UAV = []
phy-NrfMousejack = []
phy-BTLE = []
phy-METER = []
phy-ADSB = []
phy-802.15.4 = []
phy-RADIATION = []
